### ISSUE TITLE
no selection of templates in subfolders possible

### ISSUE THREAD

**Issue by Floxn** [iMi-digital/imi_template_filter#1]
only the standard templates and the (global)template are selectable. is their any way to select the template in subfolders of the templates folder?
Contao: 3.5.12
template_filter: 1.0.4

**Comment by amenk** [comment]
@Floxn Is this still relevant for you after 4 years :D ?

Should not be to hard to implement...

**Comment by Floxn** [comment]
@amenk i don´t think so :)
